name: Build Whelp Dependencies Docker Image

on:
  push:
    paths:
      - 'whelp/dockerfiles/Dockerfile.whelp'
      - 'whelp/requirements.txt'
      - 'whelp/debian_repomirror.list'
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build-whelp-dependencies:
    name: Build the Whelp tests docker image
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run `docker build`
        run: docker build -f whelp/dockerfiles/Dockerfile.whelp -t docker.repo.eng.netapp.com/global/astra/whelp-dependencies:$(echo $GITHUB_SHA | head -c7) whelp
      - name: Clean up extraneous docker artifacts
        run: docker system prune -af
